#!/bin/bash

actions="Выберите действие:\n[1] Добавить вотчер\n[2] Удалить вотчер&\n[3] Посмотреть существующие вотчеры\n"
clear

	echo -e $actions

	while ( [ 3 -eq 3 ] ) do
	read -n 1 B 
	clear
	echo -e $actions
####################################  if ! ps -e | grep -q gedit; then gedit; fi
	# Считываем команду # 
	case "$B" in 
	# Добавление нового Вотчера #  
	  "1"   )  
				m=99
				# Валидируем ввод # 
				
				while (( $m > 59 || $m < 0));
				do
					echo "Введите периодичность проверки (в минутах)"
					read m
					if [ -z $m ]; then
						m=0
					fi

					if [ ${#m} -eq 1 ]; then
						m=" "$m
					fi
				done
				echo "Введите имя процесса"

				echo "Вотчер добавлен на $h:$m"
				crontab -u $USER -l > ~/tmp
				echo "$m $h * * * mplayer $song #wd" >> ~/tmp
				crontab -u $USER ~/tmp

				;; 
	# Удаление Вотчера #
	  "2"   )  
				i=0 # счётчик
				# выводим нумерованный список Вотчеров #
				crontab -u $USER -l | grep -v "# " | grep "#wd" > ~/list.tmp
				while read line
				do
				echo "[$i] Вотчер на ${line:3:2}:${line:1:2}"
				((i++))
				done < ~/list.tmp

				# получаем номер Вотчера
				echo "Введите номер Вотчера"
				read C

				clear

				i=0
				# удаляем из crontab выбранный Вотчер
				echo -n > ~/tmp
				while read line
				do
				if ! [ $i -eq $C ]
				then
					echo "[$i] Вотчер на ${line:3:2}:${line:1:2}"
					echo "$line" >> ~/tmp
				else
					echo "[*] Вотчер на ${line:3:2}:${line:1:2}"
				fi
					((i++))
				done < ~/list.tmp
				crontab -u $USER -l | grep -v "#wd" | grep -v "# "> ~/list.tmp
				cat ~/tmp >> ~/list.tmp
				crontab -u $USER ~/list.tmp
				;;
	  "3"   )   crontab -u $USER -l | grep -v "# " | grep "#wd" > ~/tmp
				while read line
				do
					echo "Вотчер на ${line:3:2}:${line:1:2}"
				done < ~/tmp
				;;
	esac
		# чистим временные файлы 
		rm -rf ~/tmp ~/list.tmp ~/count	
	done
# fi